### ISSUE TITLE
Find header cards by regular expression

### ISSUE THREAD

**Issue by rmathar** [opencadc/nom-tam-fits#8]
It would be nice to have a method in the nom.tam.fits.Header class as follows
```
        /************************************
        * @brief Collect the header cards that match a regular expression.
        *
        * This is useful if one needs to search for a keyword that is buried under
        * some HIERARCH string conventions of unspecified depth. So to search for
        * some key like "HIERARCH OBO SUBOBO MYOBO", which would appear with the
        * key HIERARCH.OBO.SUBOBO.MYOBO in this FITS implementation, one could
        * search with regex="HIER.*MYOBO" and find it, supposed FitsFactory.setUseHierarch(true)
        * was called before creating the header.
        *
        * @param regex The generalized regular expression for the keyword search
        * @return The list of header cards that match the regular expression.
        * @since 2015-03-03
        */
        public HeaderCard[] findCards(final String regex)
        { 
                /* The collection of header cards that match.
                */
                Vector<HeaderCard> crds = new Vector<HeaderCard>() ;

                /* position pointer to start of card stack and loop over all header cards
                */
                nom.tam.util.Cursor<String,HeaderCard> iter = iterator() ;
                while ( iter.hasNext() )
                {
                        final HeaderCard card = iter.next() ;
                        /* compare with regular expression and add to output list if it does
                        */
                        if ( card.getKey().matches(regex) ) 
                                crds.add(card) ;
                }

                HeaderCard[] tmp  = new HeaderCard[crds.size()];
                return crds.toArray(tmp) ;
        } /* findCards */

```

**Comment by pdowler** [comment]
Hi,
This is a fork of the upstream project that exists because we needed to make some changes to support streaming output and the upstream development is dormant. I know the original developer well (he retired recently) but have not been able to find/contact the owner of the upstream project. Several of us in IVOA that use this library have tried so far.

So, I'm not sure about the future of this fork at this point. Ideally, I'd prefer to find a more community-based place that we'd also contribute to, but we're willing to manage it under OpenCADC if necessary. We certainly have a little more technical debt to resolve (like getting all the test code running in github workflow) before we entertain external PRs (right now I have to trust that the developer ran the tests with maven or I have to pull their branch and do it manually myself and I don't like either of those options :-)

I'll keep this in mind and we'll try to decide what the future looks like soon.
